# Python basics

Data structures documentation: https://docs.python.org/3/tutorial/datastructures.html

## Importing packages

In [1]:
import numpy as np

## Lists

In [2]:
# Creating a list
my_list = []
my_list2 = list()

my_list.append(1)
print(my_list[0])
my_list[0] = 3
print(my_list[0])

1
3


In [3]:
if my_list[0] == 3:
  print("Success")

Success


In [4]:
my_list3 = [0, 1, 2, 3, 4]
print(my_list3)
print(len(my_list3))

[0, 1, 2, 3, 4]
5


In [5]:
for i in range(len(my_list3)):
  print(my_list3[i])

0
1
2
3
4


In [6]:
for i in my_list3:
  print(my_list3.index(i))
  print(i)

0
0
1
1
2
2
3
3
4
4


In [7]:
my_list4 = [i for i in range(5)]
print(my_list4)

[0, 1, 2, 3, 4]


## Sets

In [8]:
my_set = set()
list1 = [1, 2, 3, 3, 3, 4, 5, 6]
print(list1)
set1 = set(list1)
print(set1)

[1, 2, 3, 3, 3, 4, 5, 6]
{1, 2, 3, 4, 5, 6}


## Dictionaries

In [9]:
my_dictionary = dict()
my_dictionary = {}

In [10]:
my_dictionary = {"first_name": "John", "last_name": "Doe", "Age": 30}
my_dictionary["grade"] = "Senior"

print(my_dictionary.keys())
print(my_dictionary.values())

print(f"\nFirst name: {my_dictionary['first_name']}")

dict_keys(['first_name', 'last_name', 'Age', 'grade'])
dict_values(['John', 'Doe', 30, 'Senior'])

First name: John


## Make sure to keep track of the cell order

In [11]:
def add(a, b):
  return a+b

In [12]:
a = 4
b = 6

In [13]:
print(a + b)

10


In [14]:
a = 5

# Numpy

https://numpy.org/doc/stable/user/quickstart.html

In [15]:
a = np.array([1,2,3])
print(a)
a_float = np.array([1,2,3], dtype=np.float32)
print(a_float)
print(a.astype(np.float64))

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]


In [16]:
print(type(a))
print(type(a.tolist()))
print(type(np.array(list((1,2,3)))))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [17]:
m = np.array([[1,2], [3,4]])
print(m)

[[1 2]
 [3 4]]


In [18]:
a1 = a+1
print(a1)

b = np.array([8,-9,1])
print(a + b)

[2 3 4]
[ 9 -7  4]


In [19]:
a3 = a*3
print(a3)

[3 6 9]


## Reshaping

In [20]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
c1 = c.reshape((2,5))
print(c1)
c2 = c1.reshape((5,2))
print(c2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
# operating on the columns
col1 = c1[:,0]
print(col1)

alist = [1,2,3,4]
print(alist[2:])

[0 5]
[3, 4]


## Matrix operations

In [23]:
m = np.random.rand(3,3)
print(m)

[[0.91483815 0.9417932  0.76079337]
 [0.73665775 0.45706903 0.61617976]
 [0.13417901 0.98298579 0.45361885]]


In [24]:
transpose = m.T
print(transpose)
transpose2 = np.transpose(m)
print(transpose2)


[[0.91483815 0.73665775 0.13417901]
 [0.9417932  0.45706903 0.98298579]
 [0.76079337 0.61617976 0.45361885]]
[[0.91483815 0.73665775 0.13417901]
 [0.9417932  0.45706903 0.98298579]
 [0.76079337 0.61617976 0.45361885]]


In [25]:
inverse = np.linalg.inv(m)
print(inverse)

[[ 4.10549979 -3.30444772 -2.39695332]
 [ 2.59178408 -3.22479691  0.03360189]
 [-6.83075412  7.96553556  2.84069026]]


In [26]:
a = np.array([2,3,4]).reshape(1,3)
x = np.matmul(m, a.T)
print(x)

[[7.6982294 ]
 [5.30924165]
 [5.0317908 ]]


In [27]:
x2 = np.matmul(a,m)
print(x2)

[[4.57636559 7.18673668 5.18460144]]


In [28]:
dot = np.dot(m, a.T)
print(dot)

[[7.6982294 ]
 [5.30924165]
 [5.0317908 ]]


## Ex 1. Compute euclidean distance between 2 points

In [29]:
a = np.zeros(3)
print(a)
# b = np.random.rand(3)
b = np.array([0.25, 0.25, 0.25])
print(b)


[0. 0. 0.]
[0.25 0.25 0.25]


In [30]:
print(np.linalg.norm(a-b))

0.4330127018922193


## Ex2. Compute Mean and Standard Deviation

In [31]:
a = np.random.rand(10, 3)
print(a)

[[0.5500885  0.51975308 0.74240226]
 [0.63785016 0.90007021 0.32587806]
 [0.28388976 0.76007078 0.20669311]
 [0.50530877 0.76408161 0.75478607]
 [0.99473144 0.71432825 0.38711842]
 [0.9686774  0.87449987 0.511784  ]
 [0.99910949 0.07937424 0.9828963 ]
 [0.59338085 0.40585275 0.97529102]
 [0.95465433 0.85644636 0.91179261]
 [0.33774798 0.13639389 0.5307784 ]]


In [32]:
mean1 = np.mean(a)
std1 = np.std(a)
print(mean1)
print(std1)

0.638857665721795
0.27426631576133936


In [33]:
mean2 = np.mean(a, axis=1)
std2 = np.std(a, axis=1)
print(mean2)
print(std2)

[0.60408128 0.62126614 0.41688455 0.67472549 0.69872604 0.78498709
 0.68712668 0.65817488 0.9076311  0.33497342]
[0.09858864 0.2347061  0.2447072  0.1198558  0.24830219 0.19697258
 0.42979684 0.23694399 0.04020108 0.16101876]
